# -*- coding: utf-8 -*-
"""llm_demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jmqN_YElsUkHnoQi9xxjqJeyZM_7XH_p
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# App Title
st.title("Streamlit Demo")

# Sidebar Input
st.sidebar.header("User Input")
name = st.sidebar.text_input("Enter your name:", "Guest")
age = st.sidebar.slider("Select your age:", 0, 100, 25)

# Main Section
st.header(f"Hello, {name}!")
st.write(f"You are {age} years old.")

# Generate Random Data for Plot
st.header("Random Data Visualization")
data_size = st.slider("Select number of data points:", 10, 100, 50)
data = np.random.randn(data_size)

# Create and Display Plot
fig, ax = plt.subplots()
ax.hist(data, bins=15, alpha=0.7)
ax.set_title("Histogram of Random Data")
ax.set_xlabel("Value")
ax.set_ylabel("Frequency")
st.pyplot(fig)

# Dataframe Display
st.header("Generated Data")
df = pd.DataFrame(data, columns=["Random Numbers"])
st.dataframe(df)

# Download Data as CSV
st.download_button(
    label="Download Data as CSV",
    data=df.to_csv(index=False),
    file_name="random_data.csv",
    mime="text/csv"
)
